### ISSUE TITLE
Issue on page /03_object_oriented_features/01_structs.html

### ISSUE THREAD

**Issue by akodialam** [UCHI-DB/rust-guide#2] opened 2024-03-21 15:26 UTC
Its a bit pedantic but
'struct name_of_struct {
    field1: data_type
    field2: data_type,
    field3: data_type,
}'
is missing a comma after 'field1: data_type' and further the comma after 'field3: data_type' is unnecessary

**Comment by suhailrehman** [comment] 2024-03-23 03:49
Duplicate of #1

**Closed as not planned by suhailrehman** 2024-03-23 03:49 UTC
Labels: duplicate
